variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

cache:
  paths:
    - node_modules/
    - vendor/

.test:
  stage: test
  services:
    - name: mariadb:latest
      alias: mysql
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git wget libpng-dev libxml2-dev unzip

    - docker-php-ext-install gd
    - docker-php-ext-install pdo_mysql
    - docker-php-ext-install soap
    - docker-php-ext-install xdebug

    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - php composer.phar install
  script:
    - php composer.phar ci

php71:
  extends: .test
  image: php:7.1

php72:
  extends: .test
  image: php:7.2

php73:
  extends: .test
  image: php:7.3

pages:
  stage: deploy
  image: node
  before_script:
    - npm install
  script:
    - ./deploy.sh
  after_script:
    - cp -r node_modules/swagger-ui-dist public
  artifacts:
    paths:
      - public
  only:
    - master
