name: "Deploy"
on:
  release:
    types: [published]
  workflow_dispatch:
env:
  cache-version: 1
jobs:
  package:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Cache Composer dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.composer/cache"
          key: composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install Composer dependencies"
        run: |
          composer -n install --no-dev --optimize-autoloader

      - name: "Copy deployed files"
        run: |
          mkdir dist
          cp -r setup dist/
          cp -r Skaut dist/
          cp -r vendor dist/
          cp -r v*.* dist/

      - name: "Upload artifact"
        uses: actions/upload-artifact@v5
        with:
          name: "build-artifact"
          path: dist
          include-hidden-files: true

  deploy:
    name: "Deploy the app"
    runs-on: ubuntu-latest
    needs: package
    concurrency:
      group: "deploy"
      cancel-in-progress: true
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v5
        with:
          name: "build-artifact"
          path: dist

      - name: "Deploy over FTP"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_DIR }}
