---
name: "Deploy docs"
"on":
  push:
    branches: "master"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  cache-version: 1

jobs:
  build:
    name: "Build API docs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - name: "Configure Pages"
        uses: actions/configure-pages@v6

      - name: "Cache NPM dependencies"
        uses: actions/cache@v6
        with:
          path: "~/.npm"
          key: >-
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{
            hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Create build directory"
        run: |
          cp -r node_modules/swagger-ui-dist docs-dist
          mkdir docs-dist/definitions

      - name: "Copy over API definitions"
        run: |
          for file in open-api-spec-*.yaml; do version=$(echo "$file" | grep -oP 'v\d+\.\d+' | sed 's/^v//'); [ -n "$version" ] && cp "$file" "docs-dist/definitions/v$version.yaml"; done

      - name: "Change docs title"
        run: |
          sed -i -e "/<title>Swagger UI<\/title>/c <title>Handbook API</title>" docs-dist/index.html

      - name: "Change API definitions list"
        run: |
          URLS=$(echo "    urls: [$(ls docs-dist/definitions/ | grep -E "v.*\\..*" | awk -v ORS= '{print "{url: \"https://scout-handbook.github.io/handbook-api/definitions/" $1 "\", name: \"Version " substr($1, 2, 3) "\"}, "}' | sed 's/..$//')],")
          sed -i -e "/url: \"https:\/\/petstore\.swagger\.io\/v2\/swagger\.json\",/c \\${URLS}" docs-dist/swagger-initializer.js

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs-dist

  deploy:
    name: "Deploy API docs"
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: actions/deploy-pages@v5
